---
title: "NosAnalizamos"
author: "Pablo Cucala Campesino"
date: "2026-05-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# LIBRERÍAS
```{r}
library(readr)
library(dplyr)
library(lubridate)
library(stringr)
library(forcats)
library(tidyr)
library(rticles)
library(kableExtra)
library(ggplot2)
library(pracma)
library(GGallyS)
```
# CARGA DATOS FICHERO
```{r}
datos <- read_delim("data/NosAutoanalizamos2022 - Hoja1.tsv", 
                    delim = "\t", 
                    escape_double = FALSE, #""
                    trim_ws = TRUE, #Fuera espacios en blanco
                    skip = 25) %>%
  select(-1) %>%
  filter(!is.na(Id))

```
# Eliminar a usuario
```{r}
datos <- datos %>% 
  filter(Id != "martsobm")
```
# Modificar columnas de calificaciones
```{r}
datos <- datos %>%
  mutate(across(c(ALG, ANM, FP, DCS, MD), ~ {
    # 1. Convertir a texto para manipular
    x <- as.character(.x)
    
    # 2. Sustituir coma por punto
    x <- str_replace(x, ",", ".")
    
    # 3. Sustituir "NC" por 3
    x[x == "NC"] <- "3"
    as.numeric(x) #Si no es numérico lo sustituye por NA
  }))
datos

# Guardar en Notas.Rdata como pide el enunciado
save(datos, file = "Notas.Rdata")
```
#Calcular tabla estadística
```{r}
# 1. Calcular los estadísticos en formato largo
tabla_resumen <- datos %>%
  select(ALG, ANM, FP, DCS, MD) %>%
  pivot_longer(cols = everything(), names_to = "Asignatura", values_to = "Nota") %>%
  group_by(Asignatura) %>%
  summarise(
    Minimo = min(Nota, na.rm = TRUE),
    Percentil25 = quantile(Nota, 0.25, na.rm = TRUE),
    Mediana = median(Nota, na.rm = TRUE),
    Media = mean(Nota, na.rm = TRUE),
    Desviacion_Tipica = sd(Nota, na.rm = TRUE),
    Percentil75 = quantile(Nota, 0.75, na.rm = TRUE),
    Maximo = max(Nota, na.rm = TRUE)
  ) %>%
  mutate(across(where(is.numeric), ~ round(.x, 2))) #Redondeamos a dos decimales.
tabla_resumen
```
# Gráfico con ggpairs
```{r}
notas_grafico <- datos %>%
  select(ALG, ANM, FP, DCS, MD)

# 2. Representamos las relaciones cruzadas con ggpairs
ggpairs(notas_grafico,
        title = "Relaciones cruzadas entre las calificaciones de las asignaturas",
        lower = list(continuous = wrap("points", alpha = 0.6, size = 1.5)),
        upper = list(continuous = wrap("cor", method = "pearson")))
```

# Determinar matrices de correlación
```{r}
#Matrices correlación
cat("MATRICES DE CORRELACIÓN \n")
notas_grafico <-  notas_grafico %>% na.omit()
cor_pearson  <- round(cor(notas_grafico, method = "pearson"), 2)
cor_pearson
cor_spearman  <- round(cor(notas_grafico, method = "spearman"), 2)
cor_spearman

#Las de covarianza
cat("MATRICES DE COVARIANZA \n")
cov_pearson  <- round(cov(notas_grafico, method = "pearson"), 2)
cov_pearson
cov_spearman  <- round(cov(notas_grafico, method = "spearman"), 2)
cov_spearman
```
# REPRESENTACIÓN BOXPLOTS
```{r}
datos_largos_notas <- datos %>%
  select(ALG, ANM, FP, DCS, MD) %>%
  pivot_longer(cols = everything(), 
               names_to = "Asignatura", 
               values_to = "Calificacion")

ggplot(datos_largos_notas, aes(x = Asignatura, y = Calificacion)) +
  geom_boxplot(outlier.color = "red", outlier.shape = 16) +
  labs(title = "Distribución de calificaciones por asignatura",
       x = "Asignatura",
       y = "Calificación numérica") +
  theme_minimal()

#PASO 10 (SEGÚN SEXO)
datos_largos_sexo <- datos %>%
  select(Sex, ALG, ANM, FP, DCS, MD) %>%
  pivot_longer(cols = c(ALG, ANM, FP, DCS, MD), 
               names_to = "Asignatura", 
               values_to = "Calificacion")
#Creación boxplot según sexo.
ggplot(datos_largos_sexo, aes(x = Asignatura, y = Calificacion, fill = Sex)) +
  geom_boxplot(outlier.shape = 16) +
  labs(title = "Comparativa de calificaciones por asignatura y sexo",
       x = "Asignatura",
       y = "Calificación numérica",
       fill = "Sexo") +
  theme_minimal() +
  theme(legend.position = "bottom")
```
# Selección alumnos y representación
```{r}
#Seleccionamos alumnos con notas en todas las asignaturas
datos_completos <- datos %>%
  select(Id, ALG, ANM, FP, DCS, MD) %>%
  drop_na() %>%
  pivot_longer(cols = c(ALG, ANM, FP, DCS, MD), 
               names_to = "Asignatura", 
               values_to = "Calificacion")

ggplot(datos_completos, aes(x = Id, y = Calificacion, color = Asignatura, group = Asignatura)) +
  geom_line() +
  geom_point(size = 2) +
  labs(title = "Perfil de calificaciones por alumno con convocatoria completa (2022)",
       x = "Usuario del Alumno (Id)",
       y = "Calificación Numérica",
       color = "Asignatura") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

